/*    <DR.API ZOMBIE RIOT> (c) by <De Battista Clint - (http://doyou.watch)  */
/*                                                                           */
/*                  <DR.API ZOMBIE RIOT> is licensed under a                 */
/*                        GNU General Public License                         */
/*																			 */
/*      You should have received a copy of the license along with this       */
/*            work.  If not, see <http://www.gnu.org/licenses/>.             */
//***************************************************************************//
//***************************************************************************//
//***************************DR.API ZOMBIE RIOT LOADER***********************//
//***************************************************************************//
//***************************************************************************//

#include <zombie_riot/components/variables>
#include <zombie_riot/components/globals>

#include <zombie_riot/components/hostname>

#include <zombie_riot/components/sql>

#include <zombie_riot/components/menus/menus>
#include <zombie_riot/components/menus/admins>
#include <zombie_riot/components/menus/zrhelp>

#include <zombie_riot/components/datas/daysdatas>
#include <zombie_riot/components/datas/zombiesdatas>

#include <zombie_riot/components/days>
#include <zombie_riot/components/deaths>
#include <zombie_riot/components/hud>
#include <zombie_riot/components/overlays>
#include <zombie_riot/components/sounds>

#include <zombie_riot/components/clients/teams>
#include <zombie_riot/components/clients/humans>
#include <zombie_riot/components/clients/zombies>

#include <zombie_riot/components/hooks/messages>
#include <zombie_riot/components/hooks/sdkhooks>
#include <zombie_riot/components/hooks/cvars>
#include <zombie_riot/components/hooks/events>